### ISSUE TITLE
Error with polly_xt files

### ISSUE THREAD

**Issue by aHafiz11** [nikolaos-siomos/ATLAS#8]
Hi @nikolaos-siomos,

We encountered an issue while testing ATLAS with polly_xt files:
![image](https://github.com/nikolaos-siomos/ATLAS/assets/87298036/02c7cd0f-0cb8-4f89-a180-48a395c2c87c)
We are not the cause of the error. But it seems the reader returns size 0 data from the input files.
Best,

**Comment by nikolaos-siomos** [comment]
Hi @aHafiz11,
I will have a look to the data that you uploaded. It might be a problem in your raw files that has to do with the start and end time. I remember that we discussed a similar issue during the ATLAS hands-on. What was the solution for it then?

**Comment by aHafiz11** [comment]
Hi @nikolaos-siomos,

I could not test polly_xt files during the training, I only managed to test EMORAL data.
And as I remember we discussed the issues related to files with different numbers of shots in the headers. And we solved it by removing the files with different numbers of shots from the parent directory.

**Comment by nikolaos-siomos** [comment]
The issue was fixed in v0.4.5. It was linked to the pol. calibrator angle issue where the +45, -45, and 0 positions where not identified automatically because different PollyXT systems where using different values. Both issues should be now fixed and handling of the pol. cal. variable should be done in a flexible way accounting for different values per system. Since only 4 PollyXT systems tested up to know, I will leave the issue open for a short time in case some systems still experience the same problem

**Comment by nikolaos-siomos** [comment]
Calibrator angle issue have been fixed for all PollyXT systems in version 0.4.7
